# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hss_cl_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow,QMessageBox,QInputDialog,QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 90, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 140, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 190, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 240, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 510, 91, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 570, 111, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../HSS/china_mob_1.png"))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(120, 10, 881, 251))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_6.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.openfile)
        self.pushButton_2.clicked.connect(self.openfile)
        self.pushButton_3.clicked.connect(self.openfile)
        self.pushButton_4.clicked.connect(self.openfile)
        self.pushButton_5.clicked.connect(self.openfile)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HSS测量分析"))
        self.pushButton.setText(_translate("MainWindow", "2G位置更新"))
        self.pushButton_2.setText(_translate("MainWindow", "2G被叫"))
        self.pushButton_3.setText(_translate("MainWindow", "LTE注册成功率"))
        self.pushButton_4.setText(_translate("MainWindow", "SAR消息成功率"))
        self.pushButton_5.setText(_translate("MainWindow", "UDR消息成功率"))
        self.pushButton_6.setText(_translate("MainWindow", "退出"))


class OpenCsvFile(QMainWindow):
    def __init__(self):
        self.setupUi(self)
        self.pushButton_2.clicked.connect(self.openfile)
    def openfile(self):
        path = QFileDialog.getExistingDirectory(self, "请选择文件夹", "D:/")
        self.pushButton_2.setText(str(path))
        QFileDialog.getOpenFileNames(self, "请选择测量文件", path, "CSV Files (*.CSV);;All Files (*)")